microsoft/CsWin32

- src/Microsoft.Windows.CsWin32/SourceGenerator.cs
- test/GenerationSandbox.Tests/NativeMethods.txt
Prior to this, a trailing space on a line in `NativeMethods.txt` would block generation of that API.
> Tolerate leading/trailing whitespace in NativeMethods.txt

- src/Microsoft.Windows.CsWin32/Generator.cs
A 2-character long PR: I simply modified the filename pattern so that generated files end in `.g.cs` and not simply in `.cs`. This is useful when integrating with 3rd-party code analysis tools. This way, one can easily exclude generated files from such analyses.
> Generated files now have a '.g.cs' extension

- CONTRIBUTING.md
- SECURITY.md
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/ScrapeDocs/Program.cs
I know we have a docs guideline to not use locale-specific hyperlinks, but I can't find it. @gewarren would have a link to that guideline somewhere handy?
> Make docs links locale agnostic

- README.md
- src/Microsoft.Windows.CsWin32/SourceGenerator.cs
Lines starting with "//" will be ignored when parsing NativeMethods.txt
to allow more expressive configuration files.
I've also documented the option for comments in the readme file.
This is a potential (simplistic) solution to #65.
> Added comment parsing check for  NativeMethods.txt

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/GenerationSandbox.Tests/BasicTests.cs
> Fix SafeHandle.Null to actually have a null value

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/.editorconfig
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
- test/Microsoft.Windows.CsWin32.Tests/Microsoft.Windows.CsWin32.Tests.csproj
> Generate types when referenced projects declare them internally 

- src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.csproj
- src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.nuspec
- src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.targets
- src/Microsoft.Windows.CsWin32/build/net20/Microsoft.Windows.CsWin32.props
- src/Microsoft.Windows.CsWin32/build/netstandard1.0/Microsoft.Windows.CsWin32.props
Fixes #68, when combined with https://github.com/microsoft/win32metadata/pull/194
> Arrange for msbuild import to apply to pre-net40 projects

- README.md
This is one of the ways I look for to jump over to the nuget.org page.
> Add NuGet prerelease badge to the readme to make navigation easier

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Suppress SafeHandle generation when a referencing project already declares it

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Map LARGE_INTEGER structs to 64-bit int types on .NET

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Prefer `bool` over `BOOL` in method signatures

- Directory.Build.props
- Microsoft.Windows.CsWin32.sln
- test/Directory.Build.props
- test/Microsoft.Windows.CsWin32.Tests/Microsoft.Windows.CsWin32.Tests.csproj
- test/SpellChecker/NativeMethods.txt
- test/SpellChecker/PInvoke.cs
- test/SpellChecker/Program.cs
- test/SpellChecker/SpellChecker.csproj
Shout out to @mikebattista who wrote this. I just refined it a little.
> Add SpellChecker sample

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Generate partials when the project already defines partials

- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/SignatureTypeProvider.cs
- test/GenerationSandbox.Tests/BasicTests.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
This also:
* adds support for SafeHandles that are 32-bits long even in 64-bit processes (e.g. `MSIHANDLE`).
* removes `SafeHandle` from all `extern` methods. They only appear on helper methods now.
* removes the `NullSafeHandle` static class.
Closes #129
> Make SafeHandle parameters accept null

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Add Length property to inline arrays

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
- test/SpellChecker/Program.cs
This in response to https://github.com/microsoft/CsWin32/issues/167#issuecomment-793124853
> Always use BOOL instead of `bool` in native function pointers

- src/ScrapeDocs/Program.cs
> Fix doc collection for structs ending in 32 or 64

- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/SourceGenerator.cs
> Suggest APIs for NativeMethods.txt when no match is found in the metadata

- Directory.Build.props
Updated the metadata package.
There may be more changes needed however.
See https://github.com/microsoft/win32metadata/releases/tag/v10.0.19041.5-preview.101 for the release notes to the update.
>  Update metadata to 10.0.19041.5-preview.101

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Add `[SupportedOSPlatform]` to friendly overloads

- Directory.Build.props
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/GeneratorOptions.cs
- src/Microsoft.Windows.CsWin32/HandleTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/PlatformIncompatibleException.cs
- src/Microsoft.Windows.CsWin32/TypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/templates/marshaling/CoCreateInstance.cs
- src/Microsoft.Windows.CsWin32/templates/no_marshaling/CoCreateInstance.cs
- test/GenerationSandbox.Tests/BasicTests.cs
- test/GenerationSandbox.Tests/GeneratedForm.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
- test/SpellChecker/Program.cs
* Update the metadata to 10.0.19041.202-preview
* Generate interop types into sub-namespaces. This avoids type name collisions from the metadata across namespaces and allows us to finally generate *all* APIs. Closes #31
* Discriminate code generation based on the compilation platform (i.e. CPU architecture). This gets the generation accurate for x64, x86, ARM64 where it would be different. It also _omits_ generation of anything that requires a specific platform when the platform is AnyCPU. Closes #264
> Metadata update to 10.0.19041.202-preview

- src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.csproj
This version ships with .NET Core 3.1 and therefore resolves one possible bug that shows up in [this condition][1].
[1]: https://github.com/dotnet/roslyn/issues/53672#issuecomment-860126237
> Downgrade System.Text.Json version

- src/Microsoft.Windows.CsWin32/Generator.cs
Fixes #279. This was a tough one.
> Include the period in the full-sentence link in XML docs

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
Probably not adding too much value, but easy to change too :)...
Also, \<remarks>\<para>... is generated like:
/// <para><see href="https://docs.microsoft.com/windows/win32/api/iphlpapi/nf-iphlpapi-sendarp">Learn more about this API from docs.microsoft.com.</see></para>
while the end of \<summary> is generated as:
/// <para><see href="https://docs.microsoft.com/windows/win32/api/iphlpapi/nf-iphlpapi-sendarp#parameters">Read more on docs.microsoft.com</see>.</para>
thus, beeing SA1629 compliant.
> Fix SA1629 "... should end with a period" in generated xml docs

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/GenerationSandbox.Tests/BasicTests.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Stop translating BOOL to bool

- src/Microsoft.Windows.CsWin32/PointerTypeHandleInfo.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
Fixes #269 and many other problems with DirectX2D/11/12 etc.
When parameters with `NativeArrayInfo` are marshaled `MarshalAsAttribute` is sometimes missing.
https://github.com/microsoft/CsWin32/blob/main/src/Microsoft.Windows.CsWin32/PointerTypeHandleInfo.cs#L32
In this case `marshalAs` variable corresponds to element type of the array.
When there is no need for setting specific `ArraySubType` the `MarshalAsAttribute` is dropped altogether.
It should be set to just `MarshalAs(UnmanagedType.LPArray)` without specifying `ArraySubType`.
https://github.com/microsoft/CsWin32/blob/main/src/Microsoft.Windows.CsWin32/PointerTypeHandleInfo.cs#L57
There is exactly the same code in case of marshaling structs as array. Maybe that caused some confusion.
But in that case dropping `MarshalAs` is …
> Fix marshaling of NativeArrayInfo parameters

- .github/dependabot.yml
- src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.csproj
- test/Microsoft.Windows.CsWin32.Tests/Microsoft.Windows.CsWin32.Tests.csproj
Rolls back #348, and fixes a test failure due to messagepack.annotations.dll not deploying to the test directory. 
Fixes #371
> Rollback MessagePack upgrade back to 2.2

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/GenerationSandbox.Tests/BasicTests.cs
- test/GenerationSandbox.Tests/GeneratedForm.cs
> Friendly overloads accept `string` for `PCSTR`

- src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.csproj
It breaks use inside of Roslyn
> Revert System.Text.Encodings.Web

- src/Microsoft.Windows.CsWin32/FastSyntaxFactory.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.csproj
- test/GenerationSandbox.Tests/BasicTests.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> A variety of enhancements for fixed length inline arrays

- src/Microsoft.Windows.CsWin32/FastSyntaxFactory.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- test/GenerationSandbox.Tests/BasicTests.cs
- test/GenerationSandbox.Tests/NativeMethods.txt
Without this, the .NET marshaler will assume Ansi, which is the C# default.
Fixes #389
> Apply `[StructLayout(CharSet.Unicode)]` to structs that contain the `char` type

- src/Microsoft.Windows.CsWin32/FastSyntaxFactory.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
This worksaround VS's annoying dialog when opening generated code that offers to normalize line endings (on the readonly file).
Fixes #369
> Generate code with consistent line endings

- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/GeneratorOptions.cs
- src/Microsoft.Windows.CsWin32/settings.schema.json
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
Fixes #419
The `version.json` property `className` has been renamed to `methodsClassName`.
> Allow customizing the name of the `Constants` class

- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/templates/.editorconfig
- src/Microsoft.Windows.CsWin32/templates/PCSTR.cs
- src/Microsoft.Windows.CsWin32/templates/PCWSTR.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Enable APIs using synthesized types to be used on net35

- .editorconfig
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/HandleTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/MetadataQualifiedTokens.cs
- src/Microsoft.Windows.CsWin32/SuperGenerator.cs
- src/Microsoft.Windows.CsWin32/templates/marshaling/CoCreateInstance.cs
- src/Microsoft.Windows.CsWin32/templates/no_marshaling/CoCreateInstance.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
Fix generation of interfaces that derive from or reference types in another winmd
Fixes #429
Fixes #430
Also update to .NET 6.0.100 SDK and C# 10
> Fix cross-winmd type references

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/GenerationSandbox.Tests/BasicTests.cs
- test/GenerationSandbox.Tests/NativeMethods.txt
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Generate cocreatable types as classes with `[ComImport]`

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
We were only promoting members in templates whose declaring types explicitly specified a visibility modifier.
Fixes #457
> Promote visibility of members in all templates

- src/Microsoft.Windows.CsWin32/BindingRedirects.cs
- src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.csproj
- src/Microsoft.Windows.CsWin32/ModuleInitializerAttribute.cs
This reverts #405 and applies an assembly resolver to .NET Framework processes to workaround the fact that we cannot supply binding redirects for the compiler to honor.
> Re-apply System.Text.Encodings.Web update

- src/Microsoft.Windows.CsWin32/MetadataIndex.cs
- src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.csproj
When the source generator is invoked concurrently, it would call `File.OpenRead` for each concurrent use. This maps the file content into memory. Each call gets its own mapped area, and the file will be read once per concurrent use. This ends up taking up *lots* of memory in some sessions.
In this change, we map the file *once* and create many streams based on it.
This fixes devdiv-1520804
> Avoid mapping the metadata file more than once

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/GenerationSandbox.Tests/GeneratedForm.cs
- test/GenerationSandbox.Tests/NativeMethods.txt
> Reuse .NET `NativeOverlapped` struct instead of generating our own

- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/SourceGenerator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Detect and report suspicious characters in NativeMethods.txt

- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/MetadataIndex.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Generate constants into their typedef structs wherever possible

- src/Microsoft.Windows.CsWin32/ArrayTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/HandleTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/PointerTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/TypeSyntaxAndMarshaling.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
The `MarshalAsAttribute` doesn't let us discern between 0 and unset. The C# compiler can tell and sets metadata based on the syntax. We have to lug around `NativeArrayInfo` in order to track a 0 vs. an unset value though till we're ready to emit syntax.
Fixes #372
> Add SizeParamIndex or CountConst as required to extern methods

- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/MetadataIndex.cs
- src/Microsoft.Windows.CsWin32/NamespaceMetadata.cs
This should drastically cut down on memory demands (from 1.2GB to store 128 copies of MetadataIndex to just 1 of them). It should presumably improve warmup perf as well, since we only create one index instead of 128.
> Share MetadataIndex instances across multiple generators

- src/Microsoft.Windows.CsWin32/MetadataIndex.cs
- src/Microsoft.Windows.CsWin32/SourceGenerator.cs
Now that the type ref to type def cache is shared across generators, it should have been using thread-safe patterns to access and update its cache dictionary.
> Fix thread-safety bug in MetadataIndex

- src/Microsoft.Windows.CsWin32/ArrayTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/HandleTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/MetadataIndex.cs
- src/Microsoft.Windows.CsWin32/PointerTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/SuperGenerator.cs
- src/Microsoft.Windows.CsWin32/TypeHandleInfo.cs
- test/GenerationSandbox.Tests/BasicTests.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
- Force unmarshaled fields in union structs. Fixes #292
- Propagate generation context
- Recognize that certain delegates are never declared as managed
- Fix type ref to type def conversion in light of multiple platform definitions
- Avoid marshalling in disallowed contexts
- Defend against infinite recursion in certian error conditions
- Small touch-ups
- Never emit an array when marshaling is not permitted
> Never use marshaled types in a union struct

- src/Microsoft.Windows.CsWin32/ArrayTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/HandleTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/PointerTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/PrimitiveTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/TypeHandleInfo.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Make `[In, Optional]` managed struct parameters actually optional in friendly overloads

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Give HWND an IntPtr field type

- src/Microsoft.Windows.CsWin32/ArrayTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/TypeSyntaxSettings.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Fix inline arrays when marshaling is off

- src/Microsoft.Windows.CsWin32/SourceGenerator.cs
> Trim Zero White Space

- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/MetadataIndex.cs
- src/Microsoft.Windows.CsWin32/Rental.cs
Toward a couple of the items on the list in #612:
- Calling PEReaderExtensions.GetMetadataReader is apparently quite slow because of some in-memory buffer copies. We can pool and recycle the result of this call.
- TryGetEnumName exhaustively searches all enum values in the metadata on every call. On subsequent generations, we should be able to reuse the result of this search rather than repeating it.
> Perf improvements to repeated generations

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Add Null static field to handles

- src/Microsoft.Windows.CsWin32/templates/BOOL.cs
- src/Microsoft.Windows.CsWin32/templates/BOOLEAN.cs
- test/GenerationSandbox.Tests/BoolTests.cs
- test/GenerationSandbox.Tests/BooleanTests.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
This means it has to be a lossy conversion, since `BOOL` is 4 bytes and `bool` is 1 byte. Generally .NET recommends avoiding lossy implicity operators (though explicit is ok). But for a type like this, it seems like super-high value for folks to be able to author `if (!SomeBOOL())` and have that work without casts.
Fixes #624
> Avoid overflow exceptions when converting `BOOL` to `bool`

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Add GeneratedCodeAttribute to Generated code

- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/GeneratorOptions.cs
- src/Microsoft.Windows.CsWin32/settings.schema.json
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
`SafeHandle` can be avoided in friendly overloads by adding the `useSafeHandles: false` property to the NativeMethods.json file.
Closes #605
> Add option to avoid SafeHandle friendly overloads

- src/Microsoft.Windows.CsWin32/Generator.cs
> Honour DoNotRelease on SafeHandles

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/.editorconfig
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Fix C# 11 warning on inline arrays

- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/templates/SYSTEMTIME.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Add DateTime operators to SYSTEMTIME

- src/Microsoft.Windows.CsWin32/FastSyntaxFactory.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/GeneratorOptions.cs
- src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.csproj
- src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.nuspec
- src/Microsoft.Windows.CsWin32/settings.schema.json
- test/GenerationSandbox.Tests/BasicTests.cs
- test/GenerationSandbox.Tests/GenerationSandbox.Tests.csproj
- test/GenerationSandbox.Tests/NativeMethods.json
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> A bunch of inline array improvements

- src/Microsoft.Windows.CsWin32/Generator.cs
This change does two things:
1. Exposes the Vtbl struct itself. This may be useful for CCW generation, although that is outside the scope of CsWin32 (at present, at least.)
2. Makes the generated code more trimmable by *not* using the Vtbl struct at all. Each method directly indexes into the vtbl by pointers and then casts the desired pointer to the appropriate unmanaged delegate for invocation.
For example, here is the effective code change:
```diff
internal uint AddRef()
{
fixed (ISpellChecker* pThis = &this)
-        return lpVtbl->AddRef_2(pThis);
+        return ((delegate *unmanaged [Stdcall]<IUnknown_unmanaged*,uint>)lpVtbl[1])(pThis);
}
-private Vtbl* lpVtbl;
+private void** lpVtbl;
-private struct Vtbl
+internal struct Vtbl
```
This PR has no effect on generated code when …
> Unmarshaled COM 'interface' struct trimmability

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/GenerationSandbox.Tests/BasicTests.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
This moves inline array structs that used to be nested to a shareable namespace based on their element type. Inline arrays of nested types continue to themselves be nested.
Closes #700
> Reuse inline array structs across all users

- src/Microsoft.Windows.CsWin32/Generator.cs
Adds a field like this to structs that represent COM interfaces:
```cs
/// <summary>The IID guid for this interface.</summary>
/// <value>{00000101-0000-0000-c000-000000000046}</value>
internal static readonly Guid Guid = new Guid(0x00000101, 0x0000, 0x0000, 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46);
```
Closes #711
> Add a `static readonly Guid` field to COM structs

- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/HandleTypeHandleInfo.cs
> Declare COM interface within the COM struct when allowMarshaling is false

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/GenerationSandbox.Tests/BasicTests.cs
> Fix BSTR.ToString() to not throw when the pointer is null

- src/Microsoft.Windows.CsWin32/Generator.cs
> Declare methods on COM interfaces-as-structs as `public`

- src/Microsoft.Windows.CsWin32/FastSyntaxFactory.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/templates/DECIMAL.cs
- test/GenerationSandbox.Tests/BasicTests.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Generate decimal/DECIMAL converters

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Be careful about using internal attributes declared in other assemblies

- Directory.Build.props
- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Update metadata to 37.0.34-preview

- src/Microsoft.Windows.CsWin32/FastSyntaxFactory.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
Also throw when the handle is not optional, but null is provided.
Fixes #755
> Use documented invalid handles when SafeHandle is null

- src/Microsoft.Windows.CsWin32/FastSyntaxFactory.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Observe `DangerousAddRef` result before proceeding.

- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/templates/PCSTR.cs
- src/Microsoft.Windows.CsWin32/templates/PCZZSTR.cs
- test/GenerationSandbox.Tests/BasicTests.cs
> Use Windows active code page instead of UTF8 for decoding narrow characters

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
Reverts microsoft/CsWin32#762
Per @aaronrobinsonMSFT, this isn't necessary because `DangerousAddRef` will throw rather than return having set the `ref` parameter to `false`.
> Revert "Observe `DangerousAddRef` result before proceeding."

- src/Microsoft.Windows.CsWin32/FastSyntaxFactory.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
- test/Microsoft.Windows.CsWin32.Tests/Microsoft.Windows.CsWin32.Tests.csproj
> Add IComIID interface to COM structs

- .devcontainer/Dockerfile
- Directory.Build.props
- Microsoft.Windows.CsWin32.sln
- global.json
- src/Microsoft.Windows.CsWin32/Generator.cs
- test/GenerationSandbox.Tests/GenerationSandbox.Tests.csproj
- test/GenerationSandbox.Unmarshalled.Tests/COMTests.cs
- test/GenerationSandbox.Unmarshalled.Tests/GenerationSandbox.Unmarshalled.Tests.csproj
- test/GenerationSandbox.Unmarshalled.Tests/NativeMethods.json
- test/GenerationSandbox.Unmarshalled.Tests/NativeMethods.txt
- test/GenerationSandbox.props
This way, the reference can be converted by others into a pointer and passed around without fear that the data will move.
The new property looks like this:
```cs
static ref readonly Guid IComIID.Guid
{
[MethodImpl(MethodImplOptions.AggressiveInlining)]
get
{
ReadOnlySpan<byte> data = new byte[] {
0x0B,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x46 };
return ref Unsafe.As<byte, Guid>(ref MemoryMarshal.GetReference(data));
}
}
```
Also add non-marshaling runtime test project so we can verify the emitted guid has the right value.
> Emit a stable reference to the interface guid

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
Fixes the non-compilable generated code reported in #774.
This change does _not_ turn off property declarations in COM structs. That (if necessary) can come in a follow-up change.
> Add IPicture test and fix the failure

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
- Turn off API docs generation in most tests.
- Avoid mutating SyntaxList in a loop.  This was the single worst source of bad perf in the FullGeneration test, costing 20 seconds out of 1.9 minutes.
- Add cache for slow `FindTypeSymbolIfAlreadyAvailable` method.
> Perf enhancements

- azure-pipelines/build.yml
- azure-pipelines/dotnet-test-cloud.ps1
- src/Microsoft.Windows.CsWin32/Generator.cs
Our full generation testing was actually omitting many COM interfaces. Closing that hole revealed a few bugs where we can emit C# that will not compile.
These changes address the test hole and the issues that closing it exposed.
> Fix full generation tests

- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
In full generation, the `FriendlyOverloadExtensions.g.cs` file was by far the largest (over 10MB in size). The C# compiler compiles types in parallel, so a very large type represents a huge unit of work that cannot be broken down into parallel compilations. It also means very large allocations for the string that renders the entire string. Splitting this up into one class per COM interface should help compilation performance, particularly in our full generation test.
> Distribute COM interface friendly overloads across many classes

- src/Microsoft.Windows.CsWin32/Generator.Com.cs
- src/Microsoft.Windows.CsWin32/settings.schema.json
- test/GenerationSandbox.Unmarshalled.Tests/GeneratedForm.cs
- test/GenerationSandbox.Unmarshalled.Tests/NativeMethods.json
This makes `*` a valid specifier to generate *all* APIs with `[PreserveSig]`.
> Allow PreserveSig to apply to all APIs

- src/Microsoft.Windows.CsWin32/Generator.Com.cs
- test/Microsoft.Windows.CsWin32.Tests/COMTests.cs
- Fix `hr` local colliding with parameter name
Fixes another regression from #825
- Declare PopulateVTable as a public method
> Touch-up CCW generation

- src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs
- test/GenerationSandbox.Tests/GeneratedForm.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
> Fix friendly overload handling of reserved parameters

- src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.nuspec
fd653cf352147a808af46c72aff2ba0567a3322c (merged in #843) broke the source generator in VS for Windows. Evidently removing dependencies that msbuild already ships, but are not in the roslyn subfolder, was too many.
> Bring back the certain dependencies

- src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs
Fixes #277
Use null-coalescing in friendly overload.
Generate `x ?? default(TYPE)` instead of `x.HasValue ? x.Value : default(TYPE)`.
> Null-coalescing in friendly overload

- src/Microsoft.Windows.CsWin32/Generator.Invariants.cs
> Emit an explanatory warning when users request generation of `IDispatch` or `IUnknown`

- src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/PointerTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/TypeSyntaxSettings.cs
- test/GenerationSandbox.Tests/ComRuntimeTests.cs
- test/GenerationSandbox.Tests/GenerationSandbox.Tests.csproj
- test/GenerationSandbox.Tests/NativeMethods.txt
- test/Microsoft.Windows.CsWin32.Tests/COMTests.cs
- test/SpellChecker/Program.cs
We now prefer to use `in`, `out` and `ref` modifiers on parameters instead of pointers, even on the original interface method definition. The reason is the CLR and Core CLR cannot marshal pointers across processes, but it can marshal these modifiers without a problem. Some interfaces are used across these boundaries, although CsWin32 doesn't know which. So we just err on generating interfaces that _can_ be used in this way.
This does unfortunately mean that some methods that took pointers and had overloads that took `Span<T>` no longer will, which means more marshaling and more array allocations. This only impacts the less perf-critical (and default) scenario where marshaling is allowed though, so I don't think it will be a big problem.
Fixes #860
> Fix for non-remotable COM interfaces

- doc/ArchSpecificAPIs.md
Fix syntax of `<PlatformTarget>x64<PlatformTarget>` to `<PlatformTarget>x64</PlatformTarget>`.
> Fix typo in ArchSpecificAPIs.md

- Directory.Packages.props
- src/Microsoft.Windows.CsWin32/Generator.Invariants.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/MetadataIndex.cs
- test/GenerationSandbox.Tests/GeneratedForm.cs
- test/Microsoft.Windows.CsWin32.Tests/HandleTests.cs
- test/SpellChecker/Program.cs
- test/WinRTInteropTest/NativeMethods.txt
> Update metadata to 49.0.21-preview

- src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs
- src/Microsoft.Windows.CsWin32/Generator.Invariants.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- test/GenerationSandbox.Tests/GeneratedForm.cs
- test/Microsoft.Windows.CsWin32.Tests/FriendlyOverloadTests.cs
> Recognize `MemorySizeAttribute` in metadata to improve friendly overloads

- Directory.Packages.props
- src/Microsoft.Windows.CsWin32/FastSyntaxFactory.cs
- src/Microsoft.Windows.CsWin32/Generator.Extern.cs
- src/Microsoft.Windows.CsWin32/Generator.Invariants.cs
- src/Microsoft.Windows.CsWin32/Generator.MetadataHelpers.cs
- src/Microsoft.Windows.CsWin32/Generator.Struct.cs
- src/Microsoft.Windows.CsWin32/Generator.WhitespaceRewriter.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/PrimitiveTypeHandleInfo.cs
- test/GenerationSandbox.Tests/BasicTests.cs
- test/GenerationSandbox.Tests/NativeMethods.txt
- test/Microsoft.Windows.CsWin32.Tests/COMTests.cs
- test/Microsoft.Windows.CsWin32.Tests/ExternMethodTests.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTestBase.cs
- test/Microsoft.Windows.CsWin32.Tests/StructTests.cs
Also [Add support for AssociatedEnumAttribute in the metadata](https://github.com/microsoft/CsWin32/commit/9e5a298983531ad20a50da2046de323a51febd72)
> Update metadata to 52.0.65-preview

- src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs
- src/Microsoft.Windows.CsWin32/Generator.Handle.cs
- test/Microsoft.Windows.CsWin32.Tests/FriendlyOverloadTests.cs
Some APIs return a common handle type but require the handle to be released with a less-common method. The metadata now includes this detail, and with this change, CsWin32 honors that.
Fixes microsoft/win32metadata#1581
> Use proper SafeHandle types for specific APIs

- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/templates/RECT.cs
- src/Microsoft.Windows.CsWin32/templates/SIZE.cs
- test/Microsoft.Windows.CsWin32.Tests/StructTests.cs
> Remove System.Drawing type references when the assembly isn't referenced

- Directory.Packages.props
- README.md
- src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.csproj
- src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.nuspec
- src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.targets
- test/Microsoft.Windows.CsWin32.Tests/DelegateTests.cs
- test/Microsoft.Windows.CsWin32.Tests/ExternMethodTests.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTestBase.cs
- test/Microsoft.Windows.CsWin32.Tests/HandleTests.cs
- test/Microsoft.Windows.CsWin32.Tests/StructTests.cs
- version.json
> Add the WDK as a default metadata input

- .azuredevops/dependabot.yml
- .config/dotnet-tools.json
- .devcontainer/Dockerfile
- .github/dependabot.yml
- Directory.Packages.props
- azure-pipelines.yml
- azure-pipelines/Archive-SourceCode.ps1
- azure-pipelines/dotnet.yml
- azure-pipelines/official.yml
- azure-pipelines/prepare-insertion-stages.yml
- azure-pipelines/vs-validation.yml
- global.json
- init.ps1
- Update Dockerfile
- Fix placement of $RestoreArguments construction
- Switch from `MSBuildTreatWarningsAsErrors` to `-warnaserror`
- Fix BinSkim when ApiScan won't run
- Bump .NET SDK to 7.0.302
- Parameterize and add diagnostics to InsertVersionsValues.ps1
- Fix schedule triggered source code archival
- Upgrade archive symbols task to v4
-  Consolidate two stages to just one
- Bump NB.GV to 3.6.132
- Bump CSharpIsNullAnalyzer from 0.1.329 to 0.1.495 (#204)
- Bump Microsoft.NET.Test.Sdk from 17.5.0 to 17.6.0 (#202)
- Bump dotnet-coverage from 17.7.0 to 17.7.1 (#205)
- (Hopefully) fix `nbgv` failures with `--` argument separator
- Fix indentation of commented section
- Bump Nerdbank.GitVersioning to 3.6.133
- Bump Microsoft.NET.Test.Sdk to 17.6.1
- Enable dependabot for Azure Repos
- …
> Merge latest Library.Template

- src/Microsoft.Windows.CsWin32/build/Microsoft.Windows.CsWin32.props
This fixes an issue @riverar reported in #356.
> Use MSBuild computed full paths for input metadata

- src/Microsoft.Windows.CsWin32/Generator.Extern.cs
- src/Microsoft.Windows.CsWin32/Generator.Features.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/SimpleSyntaxFactory.cs
- test/Microsoft.Windows.CsWin32.Tests/ExternMethodTests.cs
> Implement `SetLastError` ourselves on .NET when marshaling is not allowed

- src/Microsoft.Windows.CsWin32/Generator.Constant.cs
- src/Microsoft.Windows.CsWin32/Generator.Extern.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/GeneratorExtensions.cs
- src/Microsoft.Windows.CsWin32/IGenerator.cs
- src/Microsoft.Windows.CsWin32/PrimitiveTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/SourceGenerator.cs
- src/Microsoft.Windows.CsWin32/SuperGenerator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
- test/Microsoft.Windows.CsWin32.Tests/StructTests.cs
When a wildcard matches against multiple metadata assemblies, the source generator would report a senseless diagnostic to the user about an ambiguity that they cannot and need not resolve.
Fixes #988
> Fix constant wildcard ambiguity warnings

- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/templates/PInvokeClassMacros.cs
- test/GenerationSandbox.Tests/MacroTests.cs
- test/GenerationSandbox.Tests/NativeMethods.txt
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
- test/Microsoft.Windows.CsWin32.Tests/MacrosTests.cs
> Add MAKELONG and related macros

- src/Microsoft.Windows.CsWin32/FastSyntaxFactory.cs
- src/Microsoft.Windows.CsWin32/Generator.Com.cs
- src/Microsoft.Windows.CsWin32/Generator.WhitespaceRewriter.cs
- test/Microsoft.Windows.CsWin32.Tests/COMTests.cs
> FailFast instead of throw from non-HRESULT returning CCW methods

- src/Microsoft.Windows.CsWin32/Generator.InlineArrays.cs
Fixes #1014
The regression test for this requires a newer compiler than is available via nuget.org today. I have the test ready to go once we have a newer compiler available
> Emit `Unsafe.AsRef(in Value[0])`

- src/Microsoft.Windows.CsWin32/FastSyntaxFactory.cs
- src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs
> Fix NRE thrown from some COM extension methods

- src/Microsoft.Windows.CsWin32/PointerTypeHandleInfo.cs
- test/GenerationSandbox.Tests/GeneratedForm.cs
- test/GenerationSandbox.Tests/NativeMethods.txt
- test/SpellChecker/Program.cs
> Prefer pointers over `out`/`ref` for optional parameters

- src/Microsoft.Windows.CsWin32/Generator.GeneratedCode.cs
- src/Microsoft.Windows.CsWin32/Generator.TypeDef.cs
- src/Microsoft.Windows.CsWin32/templates/VARIANT_BOOL.cs
- test/GenerationSandbox.Tests/VARIANT_BOOLTests.cs
- test/Microsoft.Windows.CsWin32.Tests/StructTests.cs
> Add implicit conversions between `bool` and `VARIANT_BOOL`

- Directory.Packages.props
- src/Microsoft.Windows.CsWin32/Generator.Struct.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- test/Microsoft.Windows.CsWin32.Tests/StructTests.cs
Also update WDK metadata to 0.9.9-experimental
> Bump win32metadata to 55.0.45

- src/Microsoft.Windows.CsWin32/ArrayTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/Generator.Com.cs
- src/Microsoft.Windows.CsWin32/Generator.Constant.cs
- src/Microsoft.Windows.CsWin32/Generator.Delegate.cs
- src/Microsoft.Windows.CsWin32/Generator.Enum.cs
- src/Microsoft.Windows.CsWin32/Generator.Extern.cs
- src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs
- src/Microsoft.Windows.CsWin32/Generator.Handle.cs
- src/Microsoft.Windows.CsWin32/Generator.InlineArrays.cs
- src/Microsoft.Windows.CsWin32/Generator.MetadataHelpers.cs
- src/Microsoft.Windows.CsWin32/Generator.Struct.cs
- src/Microsoft.Windows.CsWin32/Generator.TypeDef.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/HandleTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/PointerTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/PrimitiveTypeHandleInfo.cs
- src/Microsoft.Windows.CsWin32/TypeHandleInfo.cs
- test/Microsoft.Windows.CsWin32.Tests/COMTests.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTestBase.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
Optional parameters cannot be expressed with the `ref` modifier on COM methods in order to avoid a pointer type. Doing so disallows the possibility of passing in null. Even `Unsafe.NullRef<T>()` does not work because the .NET interop layer throws `NullReferenceException` when that's done.
Instead, we leave it as a pointer type.
An alternative to this may be to declare the parameter as an array that allows `null` or exactly 1 element. But the API wouldn't describe itself very well, and enforcement wouldn't exist, leading to possible runtime failures.
Fixes #1081
--- 
This pull request includes a significant number of changes to various files in the codebase. The most important changes include adding a new enum to categorize different elements being generated in `Generator.cs`, modifying …
> Fix NullReferenceException in friendly overloads of COM methods with optional pointer parameters

- src/Microsoft.Windows.CsWin32/Generator.Extern.cs
- test/Microsoft.Windows.CsWin32.Tests/ExternMethodTests.cs
> Emit `DllImportAttribute.EntryPoint` when metadata sets it to a custom value

- src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs
- src/Microsoft.Windows.CsWin32/GeneratorOptions.cs
- src/Microsoft.Windows.CsWin32/settings.schema.json
- test/Microsoft.Windows.CsWin32.Tests/FullGenerationTests.cs
For amusing stats, generating "everything" produces 97MB of C# source code. Without friendly overloads, that number drops to 70MB.
Closes #1116
> Allow disabling of friendly overload generation

- src/Microsoft.Windows.CsWin32/Generator.Struct.cs
- test/Microsoft.Windows.CsWin32.Tests/StructTests.cs
Before this change, they were emitted as instance fields.
Fixes #1121
> Define constant members of structs as constants

- src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs
- src/Microsoft.Windows.CsWin32/Generator.Invariants.cs
- src/Microsoft.Windows.CsWin32/Generator.MetadataHelpers.cs
- src/Microsoft.Windows.CsWin32/Generator.Struct.cs
- src/Microsoft.Windows.CsWin32/PointerTypeHandleInfo.cs
- test/Microsoft.Windows.CsWin32.Tests/COMTests.cs
- test/Microsoft.Windows.CsWin32.Tests/ExternMethodTests.cs
> Always use pointers when referencing structs with variable-length inline arrays

- Directory.Packages.props
- integration-tests/nonsdk/NativeMethods.json
- integration-tests/sdk/NativeMethods.json
> Reference and ship the same version of System.Text.Encodings.Web

- src/Microsoft.Windows.CsWin32/Generator.Extern.cs
- src/Microsoft.Windows.CsWin32/Generator.Invariants.cs
> Add missing `DefaultDllImportSearchPaths` attribute to local functions

- src/Microsoft.Windows.CsWin32/Generator.Invariants.cs
> Disable attempts to generate SEH functions

- src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs
- test/Microsoft.Windows.CsWin32.Tests/FriendlyOverloadTests.cs
> Use `ReadOnlySpan<T>` instead of `Span<T>` in more places

- src/Microsoft.Windows.CsWin32/Generator.Features.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/templates/VariableLengthInlineArray`1.cs
> Avoid using `UnscopedRefAttribute` on downlevel *compilers*

- src/Microsoft.Windows.CsWin32/Generator.Struct.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/templates/VariableLengthInlineArray`2.cs
- test/GenerationSandbox.Tests/FlexibleArrayTests.cs
- test/GenerationSandbox.Tests/NativeMethods.txt
> Fixes marshaling of structs with variable length arrays of `char`

- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/MetadataCache.cs
- src/Microsoft.Windows.CsWin32/MetadataFile.cs
- src/Microsoft.Windows.CsWin32/MetadataIndex.cs
- src/Microsoft.Windows.CsWin32/SourceGenerator.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTestBase.cs
Allow deletion of the metadata files while the compiler process is running
Fixes #1324
> Allow deletion of the metadata files while the compiler process is running

- src/Microsoft.Windows.CsWin32/Generator.Features.cs
- src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs
- src/Microsoft.Windows.CsWin32/Generator.Templates.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/SimpleSyntaxFactory.cs
- src/Microsoft.Windows.CsWin32/templates/OverloadResolutionPriorityAttribute.cs
- test/Microsoft.Windows.CsWin32.Tests/ExternMethodTests.cs
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTestBase.cs
- test/SpellChecker/SpellChecker.csproj
- test/WinRTInteropTest/WinRTInteropTest.csproj
As brought up in https://github.com/microsoft/CsWin32/issues/1049#issuecomment-2607994476
C# supports using a polyfill attribute, so this works on any target framework. But it _does_ require C# 13 to reference the attribute on an API or an error results, so CsWin32 only emits or uses the attribute when C# 13 is in operation.
> Use C# 13 overload resolution attribute to improve friendly overloads

- src/Microsoft.Windows.CsWin32/Generator.Com.cs
- src/Microsoft.Windows.CsWin32/templates/IUnknownHelperMethods.cs
- test/Microsoft.Windows.CsWin32.Tests/COMTests.cs
> Fix build break when friendly methods are turned off and IUnknown is generated

- src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs
- test/GenerationSandbox.Tests/BasicTests.cs
- test/GenerationSandbox.Tests/NativeMethods.txt
- test/Microsoft.Windows.CsWin32.Tests/FriendlyOverloadTests.cs
> Improve `[Out] PWSTR` parameters in friendly overloads

- src/Microsoft.Windows.CsWin32/FastSyntaxFactory.cs
- src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs
- src/Microsoft.Windows.CsWin32/Generator.WhitespaceRewriter.cs
- test/GenerationSandbox.Tests/GeneratedForm.cs
- test/GenerationSandbox.Tests/NativeMethods.txt
- test/Microsoft.Windows.CsWin32.Tests/FriendlyOverloadTests.cs
> Friendly overloads replace `PCWSTR*` parameters with `ReadOnlySpan<string>`

- src/Microsoft.Windows.CsWin32/templates/PInvokeClassMacros.cs
- test/GenerationSandbox.Tests/MacroTests.cs
- test/GenerationSandbox.Tests/NativeMethods.txt
- test/Microsoft.Windows.CsWin32.Tests/MacrosTests.cs
1. **Macro Implementation**
- Added `LOWORD` and `HIWORD` macros to extract 16-bit segments from 32-bit values.
2. **Unit Tests**
- Introduced tests for `LOWORD` and `HIWORD` in `MacroTests.cs` to verify functionality with various test cases.
3. **Visibility Testing**
- Updated `MacrosTests.cs` to validate visibility settings for `LOWORD` and `HIWORD`.
4. **Native Methods Update**
- Included `LOWORD` and `HIWORD` in `NativeMethods.txt` for project reference.
- `src/Microsoft.Windows.CsWin32/templates/PInvokeClassMacros.cs`
- `test/GenerationSandbox.Tests/MacroTests.cs`
- `test/GenerationSandbox.Tests/NativeMethods.txt`
- `test/Microsoft.Windows.CsWin32.Tests/MacrosTests.cs`
> Implement LOWORD and HIWORD Macros for Extracting Low-Order and High-Order Words from a 32-Bit Value

- docfx/docs/3rdPartyMetadata.md
- docfx/docs/toc.yml
- src/Microsoft.Windows.CsWin32/Generator.Extern.cs
- src/Microsoft.Windows.CsWin32/Generator.Invariants.cs
- src/Microsoft.Windows.CsWin32/Generator.cs
- src/Microsoft.Windows.CsWin32/SourceGenerator.cs
- src/Microsoft.Windows.CsWin32/build/Microsoft.Windows.CsWin32.props
- test/Microsoft.Windows.CsWin32.Tests/GeneratorTestBase.cs
Also add docs for how to use it.
Closes #1307
> Add msbuild item to opt 3rd party libraries into app-local deployments

- src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs
> Fix NRE thrown from friendly overloads with optional pointer parameters

- src/Microsoft.Windows.CsWin32/Generator.TypeDef.cs
- src/Microsoft.Windows.CsWin32/templates/HRESULT.cs
PR adds support for using customized DebuggerDisplay for customized types (templates) instead of hardocoding `DebuggerDisplay` to structure's first field name. It is designed to work in a way, that when there is property named `DebuggerDisplay`, it is used instead. Actually there already were some custom DebuggerDisplays in templates, but these only work with [`SpecialTypeDefNames`](https://github.com/microsoft/CsWin32/blob/main/src/Microsoft.Windows.CsWin32/Generator.Invariants.cs#L63) because for normal types, only Members are obtained and rest of the template is thrown away and recrated including [DebuggerDisplay attribute](https://github.com/microsoft/CsWin32/blob/main/src/Microsoft.Windows.CsWin32/Generator.TypeDef.cs#L247).
PR also uses newly introduced capability and adds custom …
> Add custom DebuggerDisplay for HRESULT
