microsoft/CsWin32

src/Microsoft.Windows.CsWin32/Generator.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Generate structs with the `partial` modifier

src/Microsoft.Windows.CsWin32/Generator.cs, test/GenerationSandbox.Tests/BasicTests.cs
=> Add HRESULT struct members: Succeeded and Failed

src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.nuspec, src/Microsoft.Windows.CsWin32/tools/install.ps1, src/Microsoft.Windows.CsWin32/tools/uninstall.ps1
=> Add support for packages.config-based projects

src/Microsoft.Windows.CsWin32/Generator.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Return specific `SafeHandle` types and accept base types

src/Microsoft.Windows.CsWin32/Generator.cs, src/Microsoft.Windows.CsWin32/SignatureTypeProvider.cs, test/GenerationSandbox.Tests/BasicTests.cs, test/GenerationSandbox.Tests/NativeMethods.txt, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Reuse `SafeFileHandle` from BCL instead of creating `CloseHandleSafeHandle`

src/Microsoft.Windows.CsWin32/Generator.cs, src/Microsoft.Windows.CsWin32/SignatureTypeProvider.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Avoid generating `bool` as struct field

src/Microsoft.Windows.CsWin32/Generator.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Prefix Guid with `global::`

src/Microsoft.Windows.CsWin32/Generator.cs, src/Microsoft.Windows.CsWin32/SignatureTypeProvider.cs, test/GenerationSandbox.Tests/BasicTests.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Add extension methods so more runtimes can index into inline arrays

src/Microsoft.Windows.CsWin32/Generator.cs, src/ScrapeDocs/DocEnum.cs, src/ScrapeDocs/Program.cs
=> Add documentation about constants

README.md
```
R:\foobar>dotnet add package Microsoft.Windows.CsWin32 -pre
Specify one package reference to add.
Usage: dotnet add <PROJECT> package [options] <PACKAGE_NAME>
Arguments:
<PROJECT>        The project file to operate on. If a file is not specified, the command will search the current directory for one.
<PACKAGE_NAME>   The package reference to add.
Options:
-h, --help                          Show command line help.
-v, --version <VERSION>             The version of the package to add.
-f, --framework <FRAMEWORK>         Add the reference only when targeting a specific framework.
-n, --no-restore                    Add the reference without performing restore preview and compatibility check.
-s, --source <SOURCE>               The NuGet package source to use during the restore. …
```
=> Fix typo in README.md: --prerelease not -pre.

src/Microsoft.Windows.CsWin32/Generator.cs, test/GenerationSandbox.Tests/GeneratedForm.cs, test/GenerationSandbox.Tests/NativeMethods.txt
=> Offer implicit conversion from nint/nuint to LPARAM/WPARAM

src/Microsoft.Windows.CsWin32/Generator.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
When the attribute isn't defined, don't emit it.
This also adds a basic sanity test to ensure that at least the most basic extern method generated works on net40.
Fixes #208
=> Omit `DefaultDllImportSearchPathsAttribute` generation on older TFMs

src/Microsoft.Windows.CsWin32/Generator.cs
=> Attribute COM interfaces with [ComImport]

NOTICE.txt, global.json, src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.nuspec
- Add NOTICE.txt file
- Update SDK version
=> Add NOTICE.txt file to package

src/Microsoft.Windows.CsWin32/Generator.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
Closes #206. Specifics may depend on the conversation there.
=> Add IsNull property on pointer-sized structs

src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.nuspec, src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.targets
Also I updated the sdk-api submodule because the docs changed since then I think the submodule was probably forgotten in terms of updates so I updated it.
Fixes #261. (last pr was forced by the pull bot and so github thought it was merged as it then added no commits after that bot forced pushed it out of existence).
=> Add dependencies to package.

Directory.Build.props, src/Microsoft.Windows.CsWin32/Generator.cs, src/Microsoft.Windows.CsWin32/templates/marshaling/CoCreateInstance.cs, src/Microsoft.Windows.CsWin32/templates/no_marshaling/CoCreateInstance.cs, test/GenerationSandbox.Tests/BasicTests.cs, test/GenerationSandbox.Tests/GeneratedForm.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs, test/SpellChecker/Program.cs
This fixes the issue reported in #296
=> Update metadata version to 10.2.84-preview

README.md, src/Microsoft.Windows.CsWin32/Generator.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Generate whole namespaces on-demand

test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
Fixes a regression introduced by 8c6685a6dacd
=> Fix memory leak in testing

src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.nuspec
=> Suppress Win32Docs showing up as a runtime dependency downstream

src/Microsoft.Windows.CsWin32/Generator.cs
=> Fix detection of SupportedOSPlatformAttribute

src/Microsoft.Windows.CsWin32/Generator.cs, test/GenerationSandbox.Tests/BasicTests.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Allow fixed char array field initialization with string

src/Microsoft.Windows.CsWin32/Generator.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Check whether Span<T> exists before using it

azure-pipelines/signstep1.yml, azure-pipelines/signstep2.yml
This updates the name of the service connection to the right one.
=> Update signing service connection

src/Microsoft.Windows.CsWin32/MetadataIndex.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Allow memory-mapped file to open for shared reading

src/Microsoft.Windows.CsWin32/Generator.cs, test/GenerationSandbox.Tests/GeneratedForm.cs, test/GenerationSandbox.Tests/NativeMethods.txt
=> Automatically apply PreserveSig behavior where metadata sets the flag

src/Microsoft.Windows.CsWin32/Generator.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
Theoretically this could appear elsewhere too, but at present, the metadata only marks fields as obsolete, and we only implement what we can test.
Closes #239
=> Propagate `[Obsolete]` attribute on fields from the metadata

src/Microsoft.Windows.CsWin32/Generator.cs, test/GenerationSandbox.Tests/BasicTests.cs, test/GenerationSandbox.Tests/NativeMethods.txt, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Produce friendly overloads for in/out PWSTR parameters

src/Microsoft.Windows.CsWin32/Generator.cs, src/Microsoft.Windows.CsWin32/templates/PInvokeClassHelperMethods.cs
Based on @jnm2's suggestion in https://github.com/microsoft/CsWin32/pull/553#discussion_r874931648.
=> Switch to a simpler, inline null termination check

src/Microsoft.Windows.CsWin32/Generator.cs, test/GenerationSandbox.Tests/BasicTests.cs, test/GenerationSandbox.Tests/NativeMethods.txt, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Recognize documented invalid values for handles

test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Retarget testing from net5.0 to net6.0

src/Microsoft.Windows.CsWin32/Generator.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Add ambiguity handling when reusing symbols from multiple metadata references

src/Microsoft.Windows.CsWin32/FastSyntaxFactory.cs, src/Microsoft.Windows.CsWin32/Generator.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Fix formatting issues around for loops

src/Microsoft.Windows.CsWin32/Generator.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Allow certain debug-related libraries to load from the app directory

src/Microsoft.Windows.CsWin32/Generator.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Prefer System.IO.SeekOrigin over STREAM_SEEK

src/Microsoft.Windows.CsWin32/Generator.cs
=> Declare COM structs with `partial` modifier

src/Microsoft.Windows.CsWin32/Generator.cs, src/Microsoft.Windows.CsWin32/templates/BSTR.cs, test/GenerationSandbox.Tests/BasicTests.cs
=> Add BSTR.Length property

src/Microsoft.Windows.CsWin32/Generator.cs, src/Microsoft.Windows.CsWin32/HandleTypeHandleInfo.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs, test/SpellChecker/Program.cs
=> Emit COM interfaces with properties where possible

src/Microsoft.Windows.CsWin32/Generator.cs
=> Add visibility modifier to struct properties

src/Microsoft.Windows.CsWin32/Generator.Handle.cs
=> Prefer 0 handles to -1

src/Microsoft.Windows.CsWin32/Generator.Com.cs, test/GenerationSandbox.Unmarshalled.Tests/GeneratedForm.cs
=> Bring back Vtbl for IUnknown and IDispatch

src/Microsoft.Windows.CsWin32/Microsoft.Windows.CsWin32.nuspec
=> Drop all dependencies that the compiler provides

src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs, src/Microsoft.Windows.CsWin32/templates/PInvokeClassHelperMethods.cs
=> Allow null arguments where null-terminated strings are required

Directory.Packages.props
This gets the source generator working on Dev17.2.
Fixes #875
=> Downgrade System.Memory to 4.5.4

src/Microsoft.Windows.CsWin32/Generator.Handle.cs, src/Microsoft.Windows.CsWin32/Generator.InlineArrays.cs, src/Microsoft.Windows.CsWin32/Generator.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs
=> Fix generated code compilation break due to redundant extension methods

Directory.Packages.props, src/Microsoft.Windows.CsWin32/Generator.Invariants.cs, src/Microsoft.Windows.CsWin32/Generator.MetadataHelpers.cs, test/GenerationSandbox.Tests/BasicTests.cs, test/GenerationSandbox.Unmarshalled.Tests/GeneratedForm.cs
Also bump docs to 0.1.41-alpha
=> Bump win32metadata to 51.0.33-preview

src/Microsoft.Windows.CsWin32/Generator.cs, test/Microsoft.Windows.CsWin32.Tests/StructTests.cs
=> Fix user requests for special types

src/Microsoft.Windows.CsWin32/Generator.Com.cs
=> Remove unnecessary `fixed` statement in COM struct

src/Microsoft.Windows.CsWin32/MetadataIndex.cs, test/Microsoft.Windows.CsWin32.Tests/HandleTests.cs
=> Offer SafeHandle overloads of methods with HGDIOBJ parameters

src/Microsoft.Windows.CsWin32/Generator.Enum.cs, src/Microsoft.Windows.CsWin32/Generator.Invariants.cs, src/Microsoft.Windows.CsWin32/MetadataUtilities.cs, test/Microsoft.Windows.CsWin32.Tests/EnumTests.cs
=> Include "associated constants" in enum declarations

src/Microsoft.Windows.CsWin32/SourceGenerator.cs, test/Microsoft.Windows.CsWin32.Tests/CSharpSourceGeneratorVerifier.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorConfiguration.cs, test/Microsoft.Windows.CsWin32.Tests/SourceGeneratorTests.cs
=> Improve input error reporting

src/Microsoft.Windows.CsWin32/Generator.FriendlyOverloads.cs
=> Assume null for invalid handles where invalid values are not specified

src/Microsoft.Windows.CsWin32/SourceGenerator.cs, test/Microsoft.Windows.CsWin32.Tests/SourceGeneratorTests.cs
=> Allow generation of all functions in modules that appear in more than one metadata input

Directory.Packages.props, src/Microsoft.Windows.CsWin32/Generator.Constant.cs, src/Microsoft.Windows.CsWin32/Generator.Handle.cs, src/Microsoft.Windows.CsWin32/Generator.TypeDef.cs, test/Microsoft.Windows.CsWin32.Tests/CSharpSourceGeneratorVerifier.cs, test/Microsoft.Windows.CsWin32.Tests/ConstantsTests.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTestBase.cs, test/Microsoft.Windows.CsWin32.Tests/HandleTests.cs, test/Microsoft.Windows.CsWin32.Tests/SourceGeneratorTests.cs
=> Bump metadata to v61.0.15-preview

src/Microsoft.Windows.CsWin32/HandleTypeHandleInfo.cs, test/Microsoft.Windows.CsWin32.Tests/COMTests.cs
=> Apply `[MarshalAs(FunctionPtr)]` to function pointer parameters

src/Microsoft.Windows.CsWin32/Generator.Com.cs, src/Microsoft.Windows.CsWin32/templates/IUnknownHelperMethods.cs, test/Microsoft.Windows.CsWin32.Tests/COMTests.cs
=> Add `QueryInterface<T>` helper method

.config/dotnet-tools.json, Directory.Packages.props, init.ps1, test/Microsoft.Windows.CsWin32.Tests/COMTests.cs, test/Microsoft.Windows.CsWin32.Tests/GeneratorTests.cs, test/Microsoft.Windows.CsWin32.Tests/StructTests.cs
- **Bump dotnet-coverage from 17.12.3 to 17.12.4 (#289)**
- **Bump xunit from 2.9.0 to 2.9.1 (#290)**
- **Bump dotnet-coverage from 17.12.4 to 17.12.5 (#292)**
- **Bump xunit from 2.9.1 to 2.9.2 (#291)**
- **Install the SBOM tool from the MicroBuildToolset**
=> Merge latest Library.Template

src/Microsoft.Windows.CsWin32/Generator.GeneratedCode.cs, src/Microsoft.Windows.CsWin32/Generator.cs, test/Microsoft.Windows.CsWin32.Tests/COMTests.cs
=> Generate `WinRTCustomMarshaler` when referenced from extern methods
